# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e228bf032dea42adc6a0257280df8908"
application_url = "https://remark-kelly-il-header.trycloudflare.com"
embedded = true
name = "flexible-account-app"
handle = "flexible-account-app-12"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, write_discounts, write_discounts_allocator_functions, read_products"

[auth]
redirect_urls = [
  "https://remark-kelly-il-header.trycloudflare.com/auth/callback",
  "https://remark-kelly-il-header.trycloudflare.com/auth/shopify/callback",
  "https://remark-kelly-il-header.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
